### ISSUE TITLE
How to integrate OpenGLES with OpenWFD

### ISSUE THREAD

**Issue by bseker** [KhronosGroup/OpenWF-Registry#2]
I want to integrate OpenGLES 3.2 with OpenWFD on QNX platform. In OpenWF Display 1.0 Specification, it is stated that "Transferring image data from an OpenGL ES renderer into OpenWF Display is one example of using streams." However, I cannot find any OpenWFD API function that let me create a WFDNativeStreamType, or how to connect OpenGLES to this stream. 

I also tried using EGLImages to transfer OpenGLES render output to openwfd, however cannot accomplished anything.

Is there a way to integrate OpenGLES and OpenWFD? Thanks

**Comment by oddhack** [comment]
Unfortunately, OpenWF is not an active Khronos standard - the last spec activity was more than a decade ago. If QNX is still supporting it, then asking them would be your best hope. Sorry not to have better news.

**Comment by bseker** [comment]
Thanks for the quick reply. I wish the best
